name: Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cmake-version: ["3.21", "3.22", "3.23", "3.24", "3.25", "3.26", "3.27", "3.28", "3.29", "3.30", "3.31", "4.0", "4.1", "4.2"]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Cache Swift Environment
        id: cache-swift
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/swift
          key: ubuntu-24.04-x86_64-swift-6.2-RELEASE

      - name: Install Swift Environment
        if: steps.cache-swift.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ github.workspace }}/swift
          wget https://download.swift.org/swift-6.2-release/ubuntu2404/swift-6.2-RELEASE/swift-6.2-RELEASE-ubuntu24.04.tar.gz
          tar xf swift-6.2-RELEASE-ubuntu24.04.tar.gz --strip-components=1 -C ${{ github.workspace }}/swift

      - name: Add Swift to PATH
        run: |
          echo "${{ github.workspace }}/swift/usr/bin" >> $GITHUB_PATH

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends wget gnupg2 \
            build-essential gettext fakeroot libfcitx5core-dev libfcitx5config-dev libfcitx5utils-dev \
            ninja-build qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libqt6widgets6 libqt6gui6 qt6-l10n-tools libglx-dev libgl1-mesa-dev libxkbcommon-dev libvulkan-dev glslc

      - name: Install Dependencies (protobuf)
        run: |
          sudo apt-get install -y protobuf-compiler libprotoc-dev

      - name: Create Directories
        run: |
          mkdir -p ${{ github.workspace }}/workdir
          mkdir -p ${{ github.workspace }}/packages

      - name: Build hazkey
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          sed -i "s/Qt::Orientation::/Qt::/g" ../hazkey-settings/mainwindow.ui
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -G Ninja ..
          ninja -j$(nproc)
          env  DESTDIR=${{ github.workspace }}/workdir ninja install