name: Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cmake-version: ["3.21", "3.22", "3.23", "3.24", "3.25", "3.26", "3.27", "3.28", "3.29", "3.30", "3.31", "4.0", "4.1", "4.2"]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Cache Swift Environment
        id: cache-swift
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/swift
          key: ubuntu-22.04-x86_64-swift-6.2-RELEASE

      - name: Install Swift Environment
        if: steps.cache-swift.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ github.workspace }}/swift
          wget https://download.swift.org/swift-6.2-release/ubuntu2204/swift-6.2-RELEASE/swift-6.2-RELEASE-ubuntu22.04.tar.gz
          tar xf $(basename swift-6.2-RELEASE-ubuntu22.04.tar.gz) --strip-components=1 -C ${{ github.workspace }}/swift

      - name: Add Swift to PATH
        run: |
          echo "${{ github.workspace }}/swift/usr/bin" >> $GITHUB_PATH

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends wget gnupg2 \
            build-essential gettext fakeroot \
            ninja-build libglx-dev libgl1-mesa-dev libxkbcommon-dev

      - name: Vulkan Dependencies (Ubuntu 22.04)
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt-get update -y
          sudo apt-get install -y mesa-vulkan-drivers vulkan-sdk

      - name: Create Directories
        run: |
          mkdir -p ${{ github.workspace }}/workdir
          mkdir -p ${{ github.workspace }}/packages

      - name: Build hazkey-server
        run: |
          mkdir -p ${{ github.workspace }}/hazkey-server/build
          cd ${{ github.workspace }}/hazkey-server/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DHAZKEY_SERVER_SWIFT_LTO_MODE=full -G Ninja ..
          ninja -j$(nproc)
          env DESTDIR=${{ github.workspace }}/workdir ninja install